### ISSUE TITLE
CONTRIBUTING

### ISSUE THREAD

**Issue by tomzx** [eXolnet/redmine-code-audit#15]

**Comment by xel1045** [comment]
@tomzx , could you validate!?

**Comment by tomzx** [comment]
@xel1045 Here's a small list of CONTRIBUTING.md I looked at while trying to figure out my own.

https://github.com/xively/xively-php/blob/master/CONTRIBUTING.md
https://github.com/bobthecow/mustache.php/blob/master/CONTRIBUTING.md
https://github.com/padraic/mockery/blob/master/CONTRIBUTING.md
https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md
https://github.com/h5bp/html5-boilerplate/blob/master/CONTRIBUTING.md
https://github.com/contribute-md/contribute-md-template/blob/master/contribute.md
http://contribute.md/
https://github.com/thephpleague/factory-muffin/blob/master/CONTRIBUTING.md
https://github.com/thephpleague/fractal/blob/master/CONTRIBUTING.md

Also, a small comment, if you're looking for feedback on something, make a branch out of your changes and then create a pull request. Then it is possible to use github to track the comments on the commit and follow its evolution.

Finally, when you apply the small fix I suggested, make sure to force push instead of pushing (that is, amend the commit + push it). This should replace the b4f4cc81087df3113a3521be5a2f41b173c19197 commit with a new one.

Since this was pushed directly on the `develop` branch, you cannot really do that anymore as anyone that would have fetched the changes will have trouble fetching again if you rewrite the commit history (by amending).
