### ISSUE TITLE
Add sorting capabilities to the audit list

### ISSUE THREAD

**Issue by tomzx** [eXolnet/redmine-code-audit#28]

**Comment by xel1045** [comment]
I've added the sorting capabilities to the basic columns. However, I don't know how to do it for names. These columns (i.e. the submitter) are constructed from various fields and the display is configurable in the administration.

**Comment by xel1045** [comment]
@tomzx could you validate?

**Comment by tomzx** [comment]
Appears to work well on 2.5.1.

**Comment by tomzx** [comment]
Tested as well on 3.0.4.

I've added #65.
