### ISSUE TITLE
Audit auditors backend

### ISSUE THREAD

**Issue by tomzx** [eXolnet/redmine-code-audit#34]
Add a table which links audits to users and determines whether a user is an auditor for a particular audit.

**Comment by xel1045** [comment]
I'm not sure how it's suppose to work. On audit creation, this feature is to send an email to the auditors when an audit is required. Thus, we ask them to audit this commit.

What is suppose to happen on audit edition? What if we update this list? Maybe we should keep this feature for a later version?

**Comment by tomzx** [comment]
When an audit is edited and we 
- do not modify the auditors' list, nothing should happen (except changes done to audit description itself).
- add/remove auditors, nothing should be done, except notify the auditors of changes to the audit (much like redmine notifies watchers when an issue is modified).

The goal of this feature is to be able to have a list of auditors, which we do not have at the moment. How are we supposed to notify auditors if we don't have that?

If we are to release this for a later version, then anything related to emailing auditors should be reported back as well.

**Comment by tomzx** [comment]
I am unable to remove an auditor that was added to an audit.

**Comment by xel1045** [comment]
To verify.

**Comment by tomzx** [comment]
:+1:
