### ISSUE TITLE
Should it be possible to create multiple audits for a commit?

### ISSUE THREAD

**Issue by xel1045** [eXolnet/redmine-code-audit#40]

**Comment by tomzx** [comment]
Having a single audit for a commit would mean different people can't voice their opinion in a different thread (which can be good/bad). It would also mean that someone auditing a commit would have to potentially re-open a closed audit, which I don't particularly like.

Thus my opinion for the moment would be that it should be possible to create multiple audits from the same commit.

**Comment by xel1045** [comment]
Ok, so the current behaviour is good and no validation rule is required. I'm ok with this decision for now.
