### ISSUE TITLE
Adding inline comments is not working anymore

### ISSUE THREAD

**Issue by tomzx** [eXolnet/redmine-code-audit#51]
Most likely due to https://github.com/eXolnet/redmine-code-audit/commit/90450affa2eca30616b0097e7c72fed997e60e8e#diff-9b2ab1c1505d299b2274bb5a152659a4R5.

**Comment by xel1045** [comment]
Here's an example of the data sent when we post the form:

```
utf8:✓
authenticity_token:TnwfSZwpZSHxQcBLqJao2/LpS52tP51e3Qv4SULAs+o=
inline_comment[0][line_begin]:3
inline_comment[0][line_end]:3
inline_comment[0][change_id]:null
inline_comment[0][content]:Test
audit_action:
audit_comment:General
commit:Save
```

The `change_id` is `null`. I think it might be the source of our problem.

**Comment by tomzx** [comment]
@xel1045 you should probably not work on that stuff since I've already fixed it in my branch :stuck_out_tongue:.

See: https://github.com/TomzxForks/redmine-code-audit/tree/fixes/code-audit-js-review

**Comment by xel1045** [comment]
Well.. It's fixed on develop.
